Sprint1 Program
oier-elorrieta/E4T6 pull request #1
Opened 2024-04-26 08:13 UTC by AndoniSalsidua

2024-04-26 09:37 UTC, oier-elorrieta requested changes

2024-04-26 09:37 UTC, oier-elorrieta commented on ERRONKA4/src/DB/DBBezeroak.java
> +	    private static Connection konexioa;
Konexioak bere klase propioa izatea ez da egokiagoa?

2024-04-26 09:37 UTC, oier-elorrieta commented on ERRONKA4/src/DB/DBBezeroak.java
> +
Hau ez da sprint honetakoa. Musika deskubritu zer zerikusi dauka Bezeroarekin? Beste taula batzuetara sartzen zarete. Agian datu basearekin lan egiteko klase gehiago behar dituzue.

2024-04-26 09:37 UTC, oier-elorrieta commented on ERRONKA4/src/Modelo/Artista.java
> +public class Artista {
Lehen Sprintean POJO guztiak eskatzen ziren. Asko falta dira, herentziak, klase abstraktuak....

2024-04-26 09:37 UTC, oier-elorrieta commented on ERRONKA4/src/Vista/Artista.java
> +public class Artista extends JFrame {
Badago beste klase bat modeloan izen berdinarekin. desberdintzeko zergatik ez dituzue hauek deitzen VIzena, eso Artista_v edo Artista_leiho edo horrelako zeozer.

2024-04-26 09:37 UTC, oier-elorrieta commented on ERRONKA4/src/Vista/Artista.java
> +        comboBox.setBounds(10, 53, 205, 22);
comboBox, comboBox1 ez dira izen esanguratsuak.

2024-04-26 12:06 UTC, oier-elorrieta requested changes

2024-04-26 12:06 UTC, oier-elorrieta commented on ERRONKA4/src/Modelo/Artista.java
> +	public Artista(int id, String izena, String irudia, String deskribapena) {
Ez duzue herentzia erabiltzen... Zertarako erabiltzen dugu ze abantaila dauka?

2024-04-26 12:06 UTC, oier-elorrieta commented on ERRONKA4/src/DB/DBErregistroa.java
> +
Lerro zuriak fuera

2024-04-29 08:07 UTC, OierZub requested changes

2024-04-29 08:07 UTC, OierZub commented on ERRONKA4/src/Modelo/Audio.java
> +public class Audio {
Audioak sortuko dituzue? Pentsatu eta aztertu zuen diagrama, ze klase izan behar dute abstraktuak?

2024-04-29 09:35 UTC, oier-elorrieta approved these changes
Ez dut ikusten klase abstrakturik. Nire aldetik, aurrera jarrai dezazuen  aprobatzen dizuet, baina hori falta da.

2024-04-29 11:17 UTC, OierZub approved these changes

2024-04-29 11:17 UTC, merged